import { IcpProfile } from "@/store/icp-finder-store";

export const mockIcpProfiles: IcpProfile[] = [
  {
    id: "1",
    name: "Alex Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Senior Product Manager",
    description:
      "Product management expert with 8+ years experience in SaaS companies",
    location: "San Francisco, CA",
    skills: "Product Strategy, UX, Analytics, Agile, Go-to-market",
    education: "MBA, Stanford University",
    languages: "English, Spanish",
    followerCount: 3420,
    averageInteractionPerPostCount: 87,
    postsTopics: "Product Management, SaaS, Tech Leadership",
    matchScore: 92,
    matchReason:
      "High match based on location, role, education, and skills that align with your criteria. Strong engagement metrics and relevant post topics.",
  },
  {
    id: "2",
    name: "Sara Williams",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "UX/UI Designer",
    description: "Creative designer focused on user-centered design approaches",
    location: "New York, NY",
    skills: "UI Design, User Research, Figma, Adobe Creative Suite",
    education: "BFA in Design, Rhode Island School of Design",
    languages: "English, French",
    followerCount: 2150,
    averageInteractionPerPostCount: 59,
    postsTopics: "UX Design, Design Systems, Accessibility",
    matchScore: 85,
    matchReason:
      "Strong match on skills and education background. Located in your target region with relevant follower count and engagement metrics.",
  },
  {
    id: "3",
    name: "Michael Chen",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Software Engineering Lead",
    description: "Full-stack developer leading engineering teams",
    location: "Austin, TX",
    skills: "React, Node.js, AWS, System Architecture",
    education: "MS Computer Science, MIT",
    languages: "English, Mandarin",
    followerCount: 1850,
    averageInteractionPerPostCount: 42,
    postsTopics: "Software Development, Engineering Management, Tech Trends",
    matchScore: 78,
    matchReason:
      "Good match on technical skills and education. Lower engagement metrics than your ideal range but strong in other criteria areas.",
  },
  {
    id: "4",
    name: "Olivia Martinez",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Marketing Director",
    description: "Growth-focused marketing leader with B2B SaaS experience",
    location: "Chicago, IL",
    skills: "Digital Marketing, Content Strategy, Analytics, Demand Generation",
    education: "BA Marketing, Northwestern University",
    languages: "English, Portuguese",
    followerCount: 5300,
    averageInteractionPerPostCount: 112,
    postsTopics: "B2B Marketing, Content Strategy, MarTech",
    matchScore: 68,
    matchReason:
      "Moderately strong match with excellent engagement metrics. Location and some skills outside your primary focus areas.",
  },
  {
    id: "5",
    name: "David Kim",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Data Scientist",
    description: "Machine learning specialist focused on predictive analytics",
    location: "Seattle, WA",
    skills: "Python, TensorFlow, Data Visualization, Statistical Analysis",
    education: "PhD in Statistics, University of Washington",
    languages: "English, Korean",
    followerCount: 1420,
    averageInteractionPerPostCount: 35,
    postsTopics: "Machine Learning, Data Science, AI Ethics",
    matchScore: 62,
    matchReason:
      "Partial match on technical background but different specialization than targeted. Follower count and engagement below your specified range.",
  },
];
